version: "2"
services:
  nginx: 
    image: nginx
    container_name: nginx
    ports: 
      - 0.0.0.0:80:80
      - 0.0.0.0:81:81
    networks: 
      - app
    volumes: 
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    ports:
      - 0.0.0.0:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/mysql/master_my.conf:/etc/mysql/my.cnf
    networks:
      - app
  slave1:
    image: mysql
    container_name: slave1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 0.0.0.0:3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
    volumes:
      - ./data/slave1:/var/lib/mysql
      - ./config/mysql/slave1_my.conf:/etc/mysql/my.cnf
    links: 
      - mysql
    networks:
      - app
networks:
  app:
    external: true